import { hashPassword } from "better-auth/crypto";
import { eq } from "drizzle-orm";
import { v4 as uuidv4 } from "uuid";
import { orm, schema } from "../src/db";
import { slugify } from "../src/modules/posts/posts.utils";

const profile = process.env.AUTH_E2E_PROFILE ?? "standard";
const ADMIN_EMAIL = `admin.${profile}@auth-e2e.local`;
const ADMIN_PASSWORD = "password1234";

async function ensureUser({
  id,
  name,
  email,
  password,
  role = "user",
  emailVerified = true,
}: {
  id: string;
  name: string;
  email: string;
  password?: string;
  role?: string;
  emailVerified?: boolean;
}) {
  const [existingUser] = await orm
    .select()
    .from(schema.users)
    .where(eq(schema.users.email, email))
    .limit(1);
  if (existingUser) return existingUser;

  const [user] = await orm
    .insert(schema.users)
    .values({
      id,
      name,
      email,
      emailVerified,
      role,
      createdAt: new Date(),
      updatedAt: new Date(),
    })
    .returning();

  if (!user) throw new Error(`Failed to seed user ${email}`);

  if (password) {
    await orm.insert(schema.accounts).values({
      id: uuidv4(),
      accountId: user.id,
      providerId: "credential",
      userId: user.id,
      password: await hashPassword(password),
      createdAt: new Date(),
      updatedAt: new Date(),
    });
  }

  return user;
}

async function ensureOrganization(userId: string) {
  const organizationId = `auth-e2e-enterprise-${profile}`;
  const teamId = `auth-e2e-team-${profile}`;

  const [existingOrganization] = await orm
    .select()
    .from(schema.organizations)
    .where(eq(schema.organizations.id, organizationId))
    .limit(1);

  if (!existingOrganization) {
    await orm.insert(schema.organizations).values({
      id: organizationId,
      name: `Auth E2E Enterprise ${profile}`,
      slug: `auth-e2e-enterprise-${profile}`,
      type: "enterprise",
      createdAt: new Date(),
    });
  }

  const [existingMember] = await orm
    .select()
    .from(schema.members)
    .where(eq(schema.members.userId, userId))
    .limit(1);

  if (!existingMember) {
    await orm.insert(schema.members).values({
      id: uuidv4(),
      organizationId,
      userId,
      role: "owner",
      createdAt: new Date(),
    });
  }

  const [existingTeam] = await orm
    .select()
    .from(schema.teams)
    .where(eq(schema.teams.id, teamId))
    .limit(1);

  if (!existingTeam) {
    await orm.insert(schema.teams).values({
      id: teamId,
      name: "Editorial",
      organizationId,
      createdAt: new Date(),
      updatedAt: new Date(),
    });
  }

  const [existingTeamMember] = await orm
    .select()
    .from(schema.teamMembers)
    .where(eq(schema.teamMembers.userId, userId))
    .limit(1);

  if (!existingTeamMember) {
    await orm.insert(schema.teamMembers).values({
      id: uuidv4(),
      teamId,
      userId,
      role: "owner",
      createdAt: new Date(),
    });
  }

  return { organizationId, teamId };
}

async function seedPosts(userId: string, organizationId: string) {
  const existingPosts = await orm.select().from(schema.posts).limit(1);
  if (existingPosts.length > 0) return;

  const posts = [
    {
      title: "A small blog that protects auth changes",
      excerpt: "The first fixture post explains why the E2E app exists.",
      content:
        "This post is intentionally simple. It gives Playwright a protected application surface after authentication succeeds.",
    },
    {
      title: "Organization invites should never be guessed",
      excerpt: "Invite links are generated by Better Auth and captured by stored email previews.",
      content:
        "The E2E suite verifies that organization invitation emails contain the correct app URL and can be accepted by a new user.",
    },
  ];

  await orm.insert(schema.posts).values(
    posts.map((post, index) => ({
      id: uuidv4(),
      ...post,
      slug: `${slugify(post.title)}-${profile}-${index}`,
      authorUserId: userId,
      organizationId,
      createdAt: new Date(Date.now() - index * 60_000),
    }))
  );
}

async function seedExpiredWaitlistCode() {
  const [existing] = await orm
    .select()
    .from(schema.waitlist)
    .where(eq(schema.waitlist.code, "expired-waitlist-code"))
    .limit(1);
  if (existing) return;

  await orm.insert(schema.waitlist).values({
    id: uuidv4(),
    email: `expired.${profile}@auth-e2e.local`,
    name: "Expired Invite",
    type: "WAITLIST",
    status: "INVITED",
    code: "expired-waitlist-code",
    expiresAt: new Date(Date.now() - 60_000),
    createdAt: new Date(),
    updatedAt: new Date(),
  });
}

async function seedProvisionedClaimUser() {
  const user = await ensureUser({
    id: `auth-e2e-claim-user-${profile}`,
    name: "Provisioned Claim User",
    email: `claim.${profile}@provisioned.auth-e2e.local`,
    role: "user",
    emailVerified: false,
  });

  const [existingClaim] = await orm
    .select()
    .from(schema.waitlist)
    .where(eq(schema.waitlist.claimUserId, user.id))
    .limit(1);
  if (existingClaim) return user;

  await orm.insert(schema.waitlist).values({
    id: `auth-e2e-claim-${profile}`,
    type: "ACCOUNT_CLAIM",
    status: "INVITED",
    claimUserId: user.id,
    code: uuidv4(),
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 24 * 14),
    createdAt: new Date(),
    updatedAt: new Date(),
  });

  return user;
}

async function seed() {
  const admin = await ensureUser({
    id: `auth-e2e-admin-${profile}`,
    name: "Auth E2E Admin",
    email: ADMIN_EMAIL,
    password: ADMIN_PASSWORD,
    role: "admin",
  });
  const { organizationId } = await ensureOrganization(admin.id);
  await seedPosts(admin.id, organizationId);
  await seedExpiredWaitlistCode();
  await seedProvisionedClaimUser();

  console.info(`Seeded ${profile}. Admin login: ${ADMIN_EMAIL} / ${ADMIN_PASSWORD}`);
}

void seed();
